replicaCount: 1
containerPort: 80

healthExamination:
  http: true
  tcp: false

volumeMount: true

imagePullSecrets: ""

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - /
  tls:
    - secretName: chart-example-tls
      hosts:
        - chart-example.local

resources:
  limits:
    cpu: 40m
    memory: 80Mi
  requests:
    cpu: 40m
    memory: 80Mi

